


#SingleInstance, force

;Gui, Add, Button, x30 y30 w100 h25 gClick, Click
;Gui, Add, Edit, x30 y60 w100 vEdit, 
;Gui, Show, w300 h300, Test GUI
;return

TestArray := ["Smith"
    ,"Johnson"
    ,"Williams"
    ,"Jones"
    ,"Brown"
    ,"Davis"
    ,"Miller"
    ,"Wilson"
    ,"Moore"
    ,"Taylor"
    ,"Anderson"
    ,"Thomas"
    ,"Jackson"
    ,"White"
    ,"Harris"
    ,"Martin"
    ,"Thompson"
    ,"Garcia"
    ,"Martinez"
    ,"Robinson"
    ,"Clark"
    ,"Rodriguez"
    ,"Lewis"
    ,"Lee"
    ,"Walker"
    ,"Hall"
    ,"Allen"
    ,"Young"
    ,"Hernandez"
    ,"King"
    ,"Wright"
    ,"Lopez"
    ,"Hill"
    ,"Scott"
    ,"Green"
    ,"Adams"
    ,"Baker"
    ,"Gonzalez"
    ,"Nelson"
    ,"Carter"
    ,"Mitchell"
    ,"Perez"
    ,"Roberts"
    ,"Turner"
    ,"Phillips"
    ,"Campbell"
    ,"Parker"
    ,"Evans"
    ,"Edwards"
    ,"Collins"
    ,"Stewart"
    ,"Sanchez"
    ,"Morris"
    ,"Rogers"
    ,"Reed"
    ,"Cook"
    ,"Morgan"
    ,"Bell"
    ,"Murphy"
    ,"Bailey"
    ,"Rivera"
    ,"Cooper"
    ,"Richardson"
    ,"Cox"
    ,"Howard"
    ,"Ward"
    ,"Torres"
    ,"Peterson"
    ,"Gray"
    ,"Ramirez"
    ,"James"
    ,"Watson"
    ,"Brooks"
    ,"Kelly"
    ,"Sanders"
    ,"Price"
    ,"Bennett"
    ,"Wood"
    ,"Barnes"
    ,"Ross"
    ,"Henderson"
    ,"Coleman"
    ,"Jenkins"
    ,"Perry"
    ,"Powell"
    ,"Long"
    ,"Patterson"
    ,"Hughes"
    ,"Flores"
    ,"Washington"
    ,"Butler"
    ,"Simmons"
    ,"Foster"
    ,"Gonzales"
    ,"Bryant"
    ,"Alexander"
    ,"Russell"
    ,"Griffin"
    ,"Diaz"
    ,"Hayes"]
;msgbox % TestArray[1] ;Shows "value1"
Random, r, 1, 100
msgbox % TestArray[r] ;Shows "value1" or "value2"

;Click:
;    GuiControlGet, TestArray
;    Random, NameGenned, 1, 100
;    msgbox % TestArray[r] ;Shows "value1" or "value2"
;    ;GuiControl,, Edit, % TestArray[NameGenned]
;    Return

;GuiClose:
ExitApp