


#SingleInstance, force

;Gui, Add, Button, x30 y30 w100 h25 gClick, Click
;Gui, Add, Edit, x30 y60 w100 vEdit, 
;Gui, Show, w300 h300, Test GUI
;return

TestArray1 := ["Smith"
    ,"Johnson"
    ,"Williams"
    ,"Jones"
    ,"Brown"
    ,"Davis"
    ,"Miller"
    ,"Wilson"
    ,"Moore"
    ,"Taylor"
    ,"Anderson"
    ,"Thomas"
    ,"Jackson"
    ,"White"
    ,"Harris"
    ,"Martin"
    ,"Thompson"
    ,"Garcia"
    ,"Martinez"
    ,"Robinson"
    ,"Clark"
    ,"Rodriguez"
    ,"Lewis"
    ,"Lee"
    ,"Walker"
    ,"Hall"
    ,"Allen"
    ,"Young"
    ,"Hernandez"
    ,"King"
    ,"Wright"
    ,"Lopez"
    ,"Hill"
    ,"Scott"
    ,"Green"
    ,"Adams"
    ,"Baker"
    ,"Gonzalez"
    ,"Nelson"
    ,"Carter"
    ,"Mitchell"
    ,"Perez"
    ,"Roberts"
    ,"Turner"
    ,"Phillips"
    ,"Campbell"
    ,"Parker"
    ,"Evans"
    ,"Edwards"
    ,"Collins"
    ,"Stewart"
    ,"Sanchez"
    ,"Morris"
    ,"Rogers"
    ,"Reed"
    ,"Cook"
    ,"Morgan"
    ,"Bell"
    ,"Murphy"
    ,"Bailey"
    ,"Rivera"
    ,"Cooper"
    ,"Richardson"
    ,"Cox"
    ,"Howard"
    ,"Ward"
    ,"Torres"
    ,"Peterson"
    ,"Gray"
    ,"Ramirez"
    ,"James"
    ,"Watson"
    ,"Brooks"
    ,"Kelly"
    ,"Sanders"
    ,"Price"
    ,"Bennett"
    ,"Wood"
    ,"Barnes"
    ,"Ross"
    ,"Henderson"
    ,"Coleman"
    ,"Jenkins"
    ,"Perry"
    ,"Powell"
    ,"Long"
    ,"Patterson"
    ,"Hughes"
    ,"Flores"
    ,"Washington"
    ,"Butler"
    ,"Simmons"
    ,"Foster"
    ,"Gonzales"
    ,"Bryant"
    ,"Alexander"
    ,"Russell"
    ,"Griffin"
    ,"Diaz"
    ,"Hayes"]


TestArray2 := ["Liam "
    ,"Emma "
    ,"Noah "
    ,"Olivia "
    ,"William "
    ,"Ava "
    ,"James "
    ,"Isabella "
    ,"Oliver "
    ,"Sophia "
    ,"Benjamin "
    ,"Charlotte "
    ,"Elijah "
    ,"Mia "
    ,"Lucas "
    ,"Amelia "
    ,"Mason "
    ,"Harper "
    ,"Logan "
    ,"Evelyn "
    ,"Alexander "
    ,"Abigail "
    ,"Ethan "
    ,"Emily "
    ,"Jacob "
    ,"Elizabeth "
    ,"Michael "
    ,"Mila "
    ,"Daniel "
    ,"Ella "
    ,"Henry "
    ,"Avery "
    ,"Jackson "
    ,"Sofia "
    ,"Sebastian "
    ,"Camila "
    ,"Aiden "
    ,"Aria "
    ,"Matthew "
    ,"Scarlett "
    ,"Samuel "
    ,"Victoria "
    ,"David "
    ,"Madison "
    ,"Joseph "
    ,"Luna "
    ,"Carter "
    ,"Grace "
    ,"Owen "
    ,"Chloe "
    ,"Wyatt "
    ,"Penelope "
    ,"John "
    ,"Layla "
    ,"Jack "
    ,"Riley "
    ,"Luke "
    ,"Zoey "
    ,"Jayden "
    ,"Nora "
    ,"Dylan "
    ,"Lily "
    ,"Grayson "
    ,"Eleanor "
    ,"Levi "
    ,"Hannah "
    ,"Isaac "
    ,"Lillian "
    ,"Gabriel "
    ,"Addison "
    ,"Julian "
    ,"Aubrey "
    ,"Mateo "
    ,"Ellie "
    ,"Anthony "
    ,"Stella "
    ,"Jaxon "
    ,"Natalie "
    ,"Lincoln "
    ,"Zoe "
    ,"Joshua "
    ,"Leah "
    ,"Christopher "
    ,"Hazel "
    ,"Andrew "
    ,"Violet "
    ,"Theodore "
    ,"Aurora "
    ,"Caleb "
    ,"Savannah "
    ,"Ryan "
    ,"Audrey "
    ,"Asher "
    ,"Brooklyn "
    ,"Nathan "
    ,"Bella "
    ,"Thomas "
    ,"Claire "
    ,"Leo "
    ,"Skylar "]
;msgbox % TestArray[1] ;Shows "value1"
Random, r, 1, 100
Random, q, 1, 100
msgbox % TestArray2[q] TestArray1[r] ;Shows "value1" or "value2"

;Click:
;    GuiControlGet, TestArray
;    Random, NameGenned, 1, 100
;    msgbox % TestArray[r] ;Shows "value1" or "value2"
;    ;GuiControl,, Edit, % TestArray[NameGenned]
;    Return

;GuiClose:
ExitApp